# Generated by Django 4.2.10 on 2025-03-23 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_contaunica_contarecorrente_contaparcelada'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contarecorrente',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='contaunica',
            name='usuario',
        ),
        migrations.DeleteModel(
            name='ContaParcelada',
        ),
        migrations.DeleteModel(
            name='ContaRecorrente',
        ),
        migrations.DeleteModel(
            name='ContaUnica',
        ),
    ]
