# Generated by Django 4.2.10 on 2025-03-23 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_remove_contarecorrente_usuario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='recurrence_period',
            field=models.CharField(blank=True, choices=[('DAILY', 'Diária'), ('MONTHLY', 'Mensal'), ('YEARLY', 'Anual')], max_length=20, null=True),
        ),
    ]
