# Generated by Django 4.2.10 on 2025-03-23 21:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('expenses', '0004_alter_expense_recurrence_period'),
    ]

    operations = [
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('income_type', models.CharField(choices=[('RECURRING', 'Recorrente'), ('INSTALLMENT', 'Parcelada'), ('ONETIME', 'Única')], default='ONETIME', max_length=20)),
                ('recurrence_period', models.CharField(blank=True, choices=[('DAILY', 'Diária'), ('MONTHLY', 'Mensal'), ('YEARLY', 'Anual')], max_length=20, null=True)),
                ('next_due_date', models.DateField(blank=True, null=True)),
                ('total_installments', models.PositiveIntegerField(blank=True, null=True)),
                ('current_installment', models.PositiveIntegerField(blank=True, null=True)),
                ('installment_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='expenses.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
